export default [
  {
    id: 1,
    title: "Airbnb Clone",
    source: "https://github.com/ozgeahras/airbnb-online-experiences-clone",
    demo: "https://ozgeahras.github.io/airbnb-online-experiences-clone/",
    image: "public/assets/airbnb-clone.PNG",
    logo: "public/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 2,
    title: "Travel Journey",
    source: "https://github.com/ozgeahras/travel-journey-with-react",
    demo: "https://ozgeahras.github.io/travel-journey-with-react/",
    image: "public/assets/travel-journey-with-react.png",
    logo: "public/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 7,
    title: "Twitter Clone",
    source: "https://github.com/ozgeahras/twitter-clone",
    demo: "https://ozgeahras.github.io/twitter-clone/",
    image: "public/assets/twitter-clone.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 3,
    title: "Chrome Extension",
    source: "https://github.com/ozgeahras/chrome-extension-with-api",
    demo: "https://ozgeahras.github.io/chrome-extension-with-api/",
    image: "public/assets/chrome-extension-with-api.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 4,
    title: "Card Game",
    source: "https://github.com/ozgeahras/card-game-war-with-api",
    demo: "https://ozgeahras.github.io/card-game-war-with-api/",
    image: "public/assets/card-game-war-with-api.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 11,
    title: "Instagram Clone",
    source: "https://github.com/ozgeahras/oldagram",
    demo: "https://ozgeahras.github.io/oldagram/",
    image: "public/assets/oldagram.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 6,
    title: "Role Playing Game",
    source: "https://github.com/ozgeahras/role-playing-game",
    demo: "https://ozgeahras.github.io/role-playing-game/",
    image: "public/assets/role-playing-game.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 5,
    title: "Unit Converter",
    source: "https://github.com/ozgeahras/unit-converter",
    demo: "https://ozgeahras.github.io/unit-converter/",
    image: "public/assets/unit-converter.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 8,
    title: "Meme Picker",
    source: "https://github.com/ozgeahras/meme-picker",
    demo: "https://ozgeahras.github.io/meme-picker/",
    image: "public/assets/meme-picker.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 9,
    title: "Cookie Consent",
    source: "https://github.com/ozgeahras/cookie-app",
    demo: "https://ozgeahras.github.io/cookie-app/",
    image: "public/assets/cookie.jpeg",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 10,
    title: "Coworking Space Site",
    source: "https://github.com/ozgeahras/coworking-space-site",
    demo: "https://ozgeahras.github.io/coworking-space-site/",
    image: "public/assets/coworking-space-site.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 12,
    title: "NFT Site",
    source: "https://github.com/ozgeahras/nft-site",
    demo: "https://ozgeahras.github.io/nft-site/",
    image: "public/assets/nft-site.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 13,
    title: "Business Card",
    source: "https://github.com/ozgeahras/business-card",
    demo: "https://ozgeahras.github.io/business-card/",
    image: "public/assets/business-card.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 14,
    title: "Pacman Game",
    source: "https://github.com/ozgeahras/pacman-game",
    demo: "https://ozgeahras.github.io/pacman-game/",
    image: "public/assets/pacman-game.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 15,
    title: "To Do App",
    source: "https://github.com/ozgeahras/todo-app",
    demo: "https://ozgeahras.github.io/todo-app/",
    image: "public/assets/todo-app-img.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 16,
    title: "Slider App",
    source: "https://github.com/ozgeahras/slider-app",
    demo: "https://ozgeahras.github.io/slider-app/",
    image: "public/assets/slider-app-img.png",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 17,
    title: "BBQ Page",
    source: "https://github.com/ozgeahras/bbq-page",
    demo: "https://ozgeahras.github.io/bbq-page/",
    image: "public/assets/bbq-page.jpg",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 18,
    title: "My Emojis",
    source: "https://github.com/ozgeahras/my-emoji-app",
    demo: "https://ozgeahras.github.io/my-emoji-app/",
    image: "public/assets/my-emojis-app-picture.jpg",
    logo: "public/assets/logo/js-logo.png",
    tech: "js",
  },
];
