export default [
  {
    id: 23,
    title: "Chat GPT 4 ChatBot - Mobile App",
    source: "https://github.com/ozgeahras/GPT-4-chatbot",
    demo: "https://wise-owl-openai-chatbot.netlify.app/",
    image: "/assets/GPT-4-chatbot.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 22,
    title: "Shopping Chart - Mobile App",
    source: "https://github.com/ozgeahras/shopping-list-mobile-app",
    demo: "https://add-to-chart.netlify.app/",
    image: "/assets/shopping-app.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 22,
    title: "Movie Idea Creator - OpenAI",
    source: "https://github.com/ozgeahras/movie-creator-with-OpenAI",
    demo: "https://movie-idea-creator-openai.netlify.app/",
    image: "/assets/movie-generator-with-openai.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 21,
    title: "Tenzies Game",
    source: "https://github.com/ozgeahras/tenzies-game-react",
    demo: "https://ozgeahras.github.io/tenzies-game-react/",
    image: "/assets/tenzies-game-react.png",
    logo: "/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 20,
    title: "Notes App",
    source: "https://github.com/ozgeahras/notes-app-with-react",
    demo: "https://ozgeahras.github.io/notes-app-with-react/",
    image: "/assets/notes-app-with-react.png",
    logo: "/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 19,
    title: "Meme Generator",
    source: "https://github.com/ozgeahras/meme-generator-with-react",
    demo: "https://ozgeahras.github.io/meme-generator-with-react/",
    image: "/assets/meme-generator-with-react.png",
    logo: "/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 18,
    title: "Airbnb Clone",
    source: "https://github.com/ozgeahras/airbnb-online-experiences-clone",
    demo: "https://ozgeahras.github.io/airbnb-online-experiences-clone/",
    image: "/assets/airbnb-clone.png",
    logo: "/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 17,
    title: "Travel Journey",
    source: "https://github.com/ozgeahras/travel-journey-with-react",
    demo: "https://ozgeahras.github.io/travel-journey-with-react/",
    image: "/assets/travel-journey-with-react.png",
    logo: "/assets/logo/react-logo.png",
    tech: "react",
  },
  {
    id: 16,
    title: "Twitter Clone",
    source: "https://github.com/ozgeahras/twitter-clone",
    demo: "https://ozgeahras.github.io/twitter-clone/",
    image: "/assets/twitter-clone.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 15,
    title: "Chrome Extension",
    source: "https://github.com/ozgeahras/chrome-extension-with-api",
    demo: "https://ozgeahras.github.io/chrome-extension-with-api/",
    image: "/assets/chrome-extension-with-api.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 14,
    title: "Card Game",
    source: "https://github.com/ozgeahras/card-game-war-with-api",
    demo: "https://ozgeahras.github.io/card-game-war-with-api/",
    image: "/assets/card-game-war-with-api.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 13,
    title: "Instagram Clone",
    source: "https://github.com/ozgeahras/oldagram",
    demo: "https://ozgeahras.github.io/oldagram/",
    image: "/assets/oldagram.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 12,
    title: "Role Playing Game",
    source: "https://github.com/ozgeahras/role-playing-game",
    demo: "https://ozgeahras.github.io/role-playing-game/",
    image: "/assets/role-playing-game.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 11,
    title: "Unit Converter",
    source: "https://github.com/ozgeahras/unit-converter",
    demo: "https://ozgeahras.github.io/unit-converter/",
    image: "/assets/unit-converter.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 10,
    title: "Meme Picker",
    source: "https://github.com/ozgeahras/meme-picker",
    demo: "https://ozgeahras.github.io/meme-picker/",
    image: "/assets/meme-picker.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 9,
    title: "Cookie Consent",
    source: "https://github.com/ozgeahras/cookie-app",
    demo: "https://ozgeahras.github.io/cookie-app/",
    image: "/assets/cookie.jpeg",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 8,
    title: "Coworking Space Site",
    source: "https://github.com/ozgeahras/coworking-space-site",
    demo: "https://ozgeahras.github.io/coworking-space-site/",
    image: "/assets/coworking-space-site.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 7,
    title: "NFT Site",
    source: "https://github.com/ozgeahras/nft-site",
    demo: "https://ozgeahras.github.io/nft-site/",
    image: "/assets/nft.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 6,
    title: "Business Card",
    source: "https://github.com/ozgeahras/business-card",
    demo: "https://ozgeahras.github.io/business-card/",
    image: "/assets/businesscard.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },

  {
    id: 5,
    title: "Pacman Game",
    source: "https://github.com/ozgeahras/pacman-game",
    demo: "https://ozgeahras.github.io/pacman-game/",
    image: "/assets/pacman.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 4,
    title: "To Do App",
    source: "https://github.com/ozgeahras/todo-app",
    demo: "https://ozgeahras.github.io/todo-app/",
    image: "/assets/todo_app.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 3,
    title: "Slider App",
    source: "https://github.com/ozgeahras/slider-app",
    demo: "https://ozgeahras.github.io/slider-app/",
    image: "/assets/slider.png",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 2,
    title: "BBQ Page",
    source: "https://github.com/ozgeahras/bbq-page",
    demo: "https://ozgeahras.github.io/bbq-page/",
    image: "/assets/bbq-page.jpg",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
  {
    id: 1,
    title: "My Emojis",
    source: "https://github.com/ozgeahras/my-emoji-app",
    demo: "https://ozgeahras.github.io/my-emoji-app/",
    image: "/assets/my-emojis-app-picture.jpg",
    logo: "/assets/logo/js-logo.png",
    tech: "js",
  },
];
